name: supervised_learning
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - absl-py
    - astunparse
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h5py
    - keras
    - keras-preprocessing
    - markdown
    - numpy
    - oauthlib
    - opt-einsum
    - protobuf
    - requests
    - requests-oauthlib
    - rsa
    - six
    - tensorboard
    - tensorflow
    - tensorflow-estimator
    - termcolor
    - typing-extensions
    - werkzeug
    - wrapt